### Create New User in MongoDB
POST http://localhost:3000/api/users
Content-Type: application/json
{
  "email": "lodhisherdil1@gmail.com",
  "password": "Admin123!"
}


#<----  GOOGLE CALENDAR TESTS  --->

### Test Message LLM
POST http://localhost:3000/api/message-llm
Content-Type: application/json

{
  "userId" :"68dda625f4574d10dee8c878",
  "message": "set an event in my google calendar for September 18 2025 at 10:00 AM"
}

### Test Message LLM
POST http://localhost:3000/api/message-llm
Content-Type: application/json

{
  "userId" :"68dda625f4574d10dee8c878",
  "message": "get google calendar events from the 22 August 2023"
}


#<----  GMAIL TESTS  --->

### Test Message LLM - List Emails
POST http://localhost:3000/api/message-llm
Content-Type: application/json

{
  "userId": "68dda625f4574d10dee8c878",
  "message": "Show me my last email from past 2 days"
}

### Test Message LLM - Send Email
POST http://localhost:3000/api/message-llm
Content-Type: application/json

{
  "userId": "68dda625f4574d10dee8c878",
  "message": "Send an email to lodhisherdil1@gmail.com with subject 'Testing Alira Gmail' and body 'Hi i am testing email from LLM'"
}


#<----  GOOGLE SHEETS TESTS  --->

### Test Message LLM - Create Google Sheet
POST http://localhost:3000/api/message-llm
Content-Type: application/json

{
  "userId": "68dda625f4574d10dee8c878",
  "message": "Create a new Google Sheet called 'Test Project Tasks' with columns names: Task, Status, Due Date, Priority in the first Row"
}

### Test Message LLM - Read Sheet Data
POST http://localhost:3000/api/message-llm
Content-Type: application/json

{
  "userId": "68dda625f4574d10dee8c878",
  "message": "List down my spresheets names with ids created in last 10 days"
}

